---

# Allow builds to run for up to 30 minutes.
timeout: 1800s

steps:

# pull images

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 80-pull-fpm
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:8.0-fpm; docker pull $_DOCKER_HUB_REPO/php:8.0-fpm-composer; exit 0'
    ]

#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    id: 80-pull-cli
#    waitFor: ['-']
#    args: [
#      '-c',
#      'docker pull $_DOCKER_HUB_REPO/php:8.0-cli; docker pull $_DOCKER_HUB_REPO/php:8.0-cli-composer; exit 0'
#    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 80-pull-nginx
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:8.0-nginx; docker pull $_DOCKER_HUB_REPO/php:8.0-nginx-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 74-pull-fpm
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.4-fpm; docker pull $_DOCKER_HUB_REPO/php:7.4-fpm-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 74-pull-cli
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.4-cli; docker pull $_DOCKER_HUB_REPO/php:7.4-cli-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 74-pull-nginx
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.4-nginx; docker pull $_DOCKER_HUB_REPO/php:7.4-nginx-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 73-pull-fpm
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.3-fpm; docker pull $_DOCKER_HUB_REPO/php:7.3-fpm-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 73-pull-cli
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.3-cli; docker pull $_DOCKER_HUB_REPO/php:7.3-cli-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 73-pull-nginx
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.3-nginx; docker pull $_DOCKER_HUB_REPO/php:7.3-nginx-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 72-pull-fpm
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.2-fpm; docker pull $_DOCKER_HUB_REPO/php:7.2-fpm-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 72-pull-cli
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.2-cli; docker pull $_DOCKER_HUB_REPO/php:7.2-cli-composer; exit 0'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: 72-pull-nginx
    waitFor: ['-']
    args: [
      '-c',
      'docker pull $_DOCKER_HUB_REPO/php:7.2-nginx; docker pull $_DOCKER_HUB_REPO/php:7.2-nginx-composer; exit 0'
    ]

# ----------------------------------------------------------------------------------------------------------------------

  # 8.0-fpm

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [80-pull-fpm]
    id: 80-build-fpm
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:8.0-fpm',
      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-fpm',
      '--build-arg', 'IMAGE=php:8.0.0alpha2-fpm-alpine3.12',
      '.'
    ]


  # 8.0-fpm-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [80-build-fpm]
    id: 80-build-fpm-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:8.0-fpm-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-fpm-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:8.0-fpm',
      '-f', 'Dockerfile-composer',
      '.'
    ]

#  # 8.0-cli
#
#  - name: 'gcr.io/cloud-builders/docker'
#    waitFor: [80-pull-cli]
#    id: 80-build-cli
#    args: [
#      'build',
#      '-t', '$_DOCKER_HUB_REPO/php:8.0-cli',
#      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-cli',
#      '--build-arg', 'IMAGE=php:8.0-rc-zts-alpine3.12',
#      '.'
#    ]
#
#  # 8.0-cli-composer
#
#  - name: 'gcr.io/cloud-builders/docker'
#    waitFor: [80-build-cli]
#    id: 80-build-cli-composer
#    args: [
#      'build',
#      '-t', '$_DOCKER_HUB_REPO/php:8.0-cli-composer',
#      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-cli-composer',
#      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:8.0-cli',
#      '-f', 'Dockerfile-composer',
#      '.'
#    ]

  # 8.0-nginx

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [80-build-fpm, 80-pull-nginx]
    id: 80-build-nginx
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:8.0-nginx',
      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-nginx',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:8.0-fpm',
      '-f', 'Dockerfile-nginx',
      '.'
    ]

  # 8.0-nginx-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [80-build-nginx]
    id: 80-build-nginx-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:8.0-nginx-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:8.0-nginx-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:8.0-nginx',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# ----------------------------------------------------------------------------------------------------------------------

  # 7.4-fpm

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-pull-fpm]
    id: 74-build-fpm
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-fpm',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-fpm',
      '--build-arg', 'IMAGE=php:7.4.8-fpm-alpine3.12',
      '.'
    ]


  # 7.4-fpm-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-build-fpm]
    id: 74-build-fpm-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-fpm-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-fpm-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.4-fpm',
      '-f', 'Dockerfile-composer',
      '.'
    ]

  # 7.4-cli

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-pull-cli]
    id: 74-build-cli
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-cli',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-cli',
      '--build-arg', 'IMAGE=php:7.4.8-zts-alpine3.12',
      '.'
    ]

  # 7.4-cli-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-build-cli]
    id: 74-build-cli-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-cli-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-cli-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.4-cli',
      '-f', 'Dockerfile-composer',
      '.'
    ]

  # 7.4-nginx

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-build-fpm, 74-pull-nginx]
    id: 74-build-nginx
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-nginx',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-nginx',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.4-fpm',
      '-f', 'Dockerfile-nginx',
      '.'
    ]

  # 7.4-nginx-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [74-build-nginx]
    id: 74-build-nginx-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.4-nginx-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.4-nginx-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.4-nginx',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# ----------------------------------------------------------------------------------------------------------------------

# 7.3-fpm

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-pull-fpm]
    id: 73-build-fpm
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-fpm',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-fpm',
      '--build-arg', 'IMAGE=php:7.3.20-fpm-alpine3.12',
      '.'
    ]


# 7.3-fpm-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build-fpm]
    id: 73-build-fpm-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-fpm-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-fpm-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.3-fpm',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# 7.3-cli

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-pull-cli]
    id: 73-build-cli
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-cli',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-cli',
      '--build-arg', 'IMAGE=php:7.3.20-zts-alpine3.12',
      '.'
    ]

# 7.3-cli-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build-cli]
    id: 73-build-cli-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-cli-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-cli-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.3-cli',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# 7.3-nginx

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build-fpm, 73-pull-nginx]
    id: 73-build-nginx
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-nginx',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-nginx',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.3-fpm',
      '-f', 'Dockerfile-nginx',
      '.'
    ]

# 7.3-nginx-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [73-build-nginx]
    id: 73-build-nginx-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.3-nginx-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.3-nginx-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.3-nginx',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# ----------------------------------------------------------------------------------------------------------------------

# 7.2-fpm

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-pull-fpm]
    id: 72-build-fpm
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-fpm',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-fpm',
      '--build-arg', 'IMAGE=php:7.2.32-fpm-alpine3.12',
      '.'
    ]


# 7.2-fpm-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build-fpm]
    id: 72-build-fpm-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-fpm-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-fpm-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.2-fpm',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# 7.2-cli

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-pull-cli]
    id: 72-build-cli
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-cli',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-cli',
      '--build-arg', 'IMAGE=php:7.2.32-zts-alpine3.12',
      '.'
    ]

# 7.2-cli-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build-cli]
    id: 72-build-cli-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-cli-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-cli-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.2-cli',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# 7.2-nginx

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build-fpm, 72-pull-nginx]
    id: 72-build-nginx
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-nginx',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-nginx',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.2-fpm',
      '-f', 'Dockerfile-nginx',
      '.'
    ]

# 7.2-nginx-composer

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [72-build-nginx]
    id: 72-build-nginx-composer
    args: [
      'build',
      '-t', '$_DOCKER_HUB_REPO/php:7.2-nginx-composer',
      '--cache-from', '$_DOCKER_HUB_REPO/php:7.2-nginx-composer',
      '--build-arg', 'IMAGE=$_DOCKER_HUB_REPO/php:7.2-nginx',
      '-f', 'Dockerfile-composer',
      '.'
    ]

# ----------------------------------------------------------------------------------------------------------------------

# Login and push images.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-username
    waitFor: ['-']
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-username.enc'
      - '--plaintext-file=docker-hub-username.txt'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-password
    waitFor: ['-']
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-password.enc'
      - '--plaintext-file=docker-hub-password.txt'

  - name: 'gcr.io/cloud-builders/docker'
    waitFor:
      - 72-build-fpm-composer
      - 72-build-cli-composer
      - 72-build-nginx-composer
      - 73-build-fpm-composer
      - 73-build-cli-composer
      - 73-build-nginx-composer
      - 74-build-fpm-composer
      - 74-build-cli-composer
      - 74-build-nginx-composer
      - decrypt-hub-username
      - decrypt-hub-password
    entrypoint: 'bash'
    args: ['-c', 'cat docker-hub-password.txt | docker login --username=$$(cat docker-hub-username.txt) --password-stdin']

images:
  - '$_DOCKER_HUB_REPO/php'
