ARG IMAGE
FROM $IMAGE

RUN set -e; \
    apk add --no-cache nginx; \
    cd /etc/nginx; \
    rm -rf conf.d fastcgi* *.default *_params; \
    mkdir -p /var/tmp/nginx; \
    chown -R www-data:www-data /var/tmp/nginx;

COPY fs-nginx/ /

ENV GZIP_TYPES="application/ecmascript application/javascript application/json application/xhtml+xml application/xml text/css text/ecmascript text/javascript text/plain text/xml" \
    LISTEN="/var/run/php-fpm.sock" \
    PORT=80 \
    ROOT="/app/public" \
    STATUS_HOSTS_ALLOWED="172.16.0.0/12 127.0.0.1" \
    STATUS_HOSTS_DENIED="all"
