ARG IMAGE
FROM $IMAGE
COPY --from=composer:1.10.6 /usr/bin/composer /usr/local/bin/composer
RUN php -n /usr/local/bin/composer global require hirak/prestissimo; \
    php -n /usr/local/bin/composer update || true
