#!/usr/bin/env sh

cat <<EOT > "$(php-config --ini-dir)/zz-config-ini-xdebug.ini"
xdebug.client_host = "${INI_XDEBUG_CLIENT_HOST:-host.docker.internal}"
xdebug.client_port = ${INI_XDEBUG_CLIENT_PORT:-9003}
xdebug.idekey = "${INI_XDEBUG_IDEKEY:-IDEKEY}"
xdebug.log = "${INI_XDEBUG_LOG:-/tmp/xdebug.log}"
xdebug.log_level = ${INI_XDEBUG_LOG_LEVEL:-3}
EOT
