#!/usr/bin/env sh

cat <<EOT > "$(php-config --ini-dir)/zz-config-ini-opcache.ini"
opcache.enable = ${INI_OPCACHE_ENABLE:-true}
opcache.enable_cli = ${INI_OPCACHE_ENABLE_CLI:-false}
opcache.max_accelerated_files = ${INI_OPCACHE_MAX_ACCELERATED_FILES:-10000}
opcache.validate_timestamps = ${INI_OPCACHE_VALIDATE_TIMESTAMPS:-true}
opcache.revalidate_freq = ${INI_OPCACHE_REVALIDATE_FREQ:-2}
opcache.save_comments = ${INI_OPCACHE_SAVE_COMMENTS:-true}
opcache.preload = ${INI_OPCACHE_PRELOAD}
EOT
