#!/usr/bin/env sh

set -e

# Determine the type of socket.
if echo "$LISTEN" | grep -q "/"; then
    socat_connect_prefix="unix-connect"
else
    socat_connect_prefix="tcp-connect"
fi

exec socat /dev/null "${socat_connect_prefix}:${LISTEN}" 2>/dev/null
