#!/usr/bin/env sh

# Attempt to figure out the default timezone to use.
if [ "$INI_DATE_TIMEZONE" != "" ]; then
  tz="$INI_DATE_TIMEZONE"
elif [ "$TZ" != "" ]; then
  tz="$TZ"
else
  tz="Etc/UTC"
fi

# Ensure the session directory exists & is writable.
if [ "$INI_SESSION_SAVE_HANDLER" = "files" ] && [ ! -d "$INI_SESSION_SAVE_PATH" ]; then
  mkdir -p "$INI_SESSION_SAVE_PATH"
  chown -R www-data:www-data "$INI_SESSION_SAVE_PATH"
fi

cat <<EOT > "$(php-config --ini-dir)/zz-config-ini-core.ini"
expose_php = ${INI_EXPOSE_PHP}
display_errors = ${INI_DISPLAY_ERRORS}
error_reporting = ${INI_ERROR_REPORTING}
html_errors = ${INI_HTML_ERRORS}
max_execution_time = ${INI_MAX_EXECUTION_TIME}
max_input_time = ${INI_MAX_INPUT_TIME}
memory_limit = ${INI_MEMORY_LIMIT}
post_max_size = ${INI_POST_MAX_SIZE}
sys_temp_dir = ${INI_SYS_TEMP_DIR}
upload_max_filesize = ${INI_UPLOAD_MAX_FILESIZE}
date.timezone = ${tz}
session.save_handler = ${INI_SESSION_SAVE_HANDLER}
session.save_path = ${INI_SESSION_SAVE_PATH}
session.name = ${INI_SESSION_NAME}
EOT
